const iconMap: Record<string, string> = {
  'code.exe':              'ti-brand-vscode',
  'cursor.exe':            'ti-brand-vscode',
  'windsurf.exe':          'ti-brand-vscode',
  'opencode.exe':          'ti-terminal-2',
  'devenv.exe':            'ti-brand-visual-studio',
  'rider64.exe':           'ti-brand-rider',
  'rider.exe':             'ti-brand-rider',
  'idea64.exe':            'ti-brand-intellij',
  'pycharm64.exe':         'ti-brand-pycharm',
  'webstorm64.exe':        'ti-brand-webstorm',
  'sublime_text.exe':      'ti-brand-sublime',
  'notepad++.exe':         'ti-file-code',
  'notepadplusplus.exe':   'ti-file-code',
  'figma.exe':             'ti-brand-figma',
  'photoshop.exe':         'ti-photo',
  'illustrator.exe':       'ti-brush',
  'blender.exe':           'ti-box',
  'chrome.exe':            'ti-brand-chrome',
  'msedge.exe':            'ti-brand-edge',
  'firefox.exe':           'ti-brand-firefox',
  'brave.exe':             'ti-brand-brave',
  'zen.exe':               'ti-brand-firefox',
  'spotify.exe':           'ti-brand-spotify',
  'discord.exe':           'ti-brand-discord',
  'slack.exe':             'ti-brand-slack',
  'teams.exe':             'ti-brand-teams',
  'zoom.exe':              'ti-brand-zoom',
  'telegram.exe':          'ti-brand-telegram',
  'whatsapp.exe':          'ti-brand-whatsapp',
  'notion.exe':            'ti-brand-notion',
  'obsidian.exe':          'ti-brand-notion',
  'terminal.exe':          'ti-terminal-2',
  'windowsterminal.exe':   'ti-terminal-2',
  'cmd.exe':               'ti-terminal-2',
  'powershell.exe':        'ti-terminal-2',
  'pwsh.exe':              'ti-terminal-2',
  'git-bash.exe':          'ti-brand-git',
  'github desktop.exe':    'ti-brand-github',
  'gitkraken.exe':         'ti-brand-git',
  'excel.exe':             'ti-file-spreadsheet',
  'winword.exe':           'ti-file-text',
  'powerpnt.exe':          'ti-presentation',
  'outlook.exe':           'ti-mail',
  'onenote.exe':           'ti-notebook',
  'explorer.exe':          'ti-folder',
  'steam.exe':             'ti-brand-steam',
  'vlc.exe':               'ti-player-play',
  'sumatrapdf.exe':        'ti-file-type-pdf',
  'acrobat.exe':           'ti-file-type-pdf',
  'dbeaver.exe':           'ti-database',
  'datagrip.exe':          'ti-database',
  'postman.exe':           'ti-api',
  'docker':                'ti-brand-docker',
  'putty.exe':             'ti-terminal-2',
  'filezilla.exe':         'ti-file-upload',
  'notepad.exe':           'ti-notes',
  'taskmgr.exe':           'ti-chart-dots',
  'calculatorapp.exe':     'ti-calculator',
  'anydesk.exe':           'ti-screen-share',
  'teamviewer.exe':        'ti-screen-share',
  'netflix':               'ti-movie',
  'youtube':               'ti-brand-youtube',
  'twitch':                'ti-brand-twitch',
  'spotify.com':           'ti-brand-spotify',
  'discord.com':           'ti-brand-discord',
  'github.com':            'ti-brand-github',
  'reddit.com':            'ti-brand-reddit',
};

export function appIcon(exeName: string): string | null {
  const key = exeName.toLowerCase();
  if (iconMap[key]) return iconMap[key];
  // Partial match for browser titles containing known domains
  for (const [k, v] of Object.entries(iconMap)) {
    if (key.includes(k)) return v;
  }
  return null;
}
