const iconMap: Record<string, string> = {
  // ── Browsers & Web ──
  'chrome.exe':          'ti-brand-chrome',
  'firefox.exe':         'ti-brand-firefox',
  'msedge.exe':          'ti-brand-edge',
  'microsoftedge.exe':   'ti-brand-edge',
  'brave.exe':           'ti-brand-brave',
  'opera.exe':           'ti-brand-opera',
  'zen.exe':             'ti-browser',
  'safari.exe':          'ti-brand-safari',
  'vivaldi.exe':         'ti-brand-vivaldi',
  'arc.exe':             'ti-brand-arc',
  'thorium.exe':         'ti-brand-chrome',
  'youtube.com':         'ti-brand-youtube',
  'twitch.tv':           'ti-brand-twitch',
  'netflix.com':         'ti-movie',
  'netflix':             'ti-movie',
  'claude.ai':           'ti-sparkles',
  'openai.com':          'ti-brand-openai',
  'chatgpt.com':         'ti-brand-openai',
  '127.0.0.1':           'ti-device-desktop',
  'localhost':           'ti-device-desktop',

  // ── Development Tools ──
  'code.exe':            'ti-brand-vscode',
  'code - insiders.exe': 'ti-brand-vscode',
  'cursor.exe':          'ti-brand-vscode',
  'windsurf.exe':        'ti-brand-vscode',
  'opencode.exe':        'ti-brand-vscode',
  'devenv.exe':          'ti-brand-visual-studio',
  'rider64.exe':         'ti-brand-rider',
  'rider.exe':           'ti-brand-rider',
  'idea64.exe':          'ti-brand-intellij',
  'idea.exe':            'ti-brand-intellij',
  'pycharm64.exe':       'ti-brand-pycharm',
  'pycharm.exe':         'ti-brand-pycharm',
  'webstorm64.exe':      'ti-brand-webstorm',
  'webstorm.exe':        'ti-brand-webstorm',
  'phpstorm64.exe':      'ti-brand-php',
  'phpstorm.exe':        'ti-brand-php',
  'goland64.exe':        'ti-brand-golang',
  'goland.exe':          'ti-brand-golang',
  'clion64.exe':         'ti-brand-clion',
  'clion.exe':           'ti-brand-clion',
  'datagrip64.exe':      'ti-database',
  'datagrip.exe':        'ti-database',
  'dataspell64.exe':     'ti-database',
  'dataspell.exe':       'ti-database',
  'studio64.exe':        'ti-brand-android',
  'android studio.exe':  'ti-brand-android',
  'xcode.exe':           'ti-brand-apple',
  'eclipse.exe':         'ti-brand-eclipse',
  'sublime_text.exe':    'ti-brand-sublime',
  'notepad++.exe':       'ti-file-code',
  'notepadplusplus.exe': 'ti-file-code',
  'notepad.exe':         'ti-notes',
  'nvim.exe':            'ti-brand-vim',
  'vim.exe':             'ti-brand-vim',
  'gvim.exe':            'ti-brand-vim',
  'neovide.exe':         'ti-brand-vim',
  'emacs.exe':           'ti-letter-e',
  'hx.exe':              'ti-letter-h',
  'atom.exe':            'ti-brand-atom',
  'zed.exe':             'ti-file-code',
  'trae.exe':            'ti-brand-vscode',
  'trae_cn.exe':         'ti-brand-vscode',

  // ── Terminals & Shells ──
  'windowsterminal.exe': 'ti-terminal-2',
  'terminal.exe':        'ti-terminal-2',
  'cmd.exe':             'ti-terminal',
  'powershell.exe':      'ti-brand-powershell',
  'pwsh.exe':            'ti-brand-powershell',
  'conhost.exe':         'ti-terminal-2',
  'git-bash.exe':        'ti-brand-git',
  'wsl.exe':             'ti-brand-ubuntu',
  'ubuntu.exe':          'ti-brand-ubuntu',
  'debian.exe':          'ti-brand-ubuntu',
  'alacritty.exe':       'ti-terminal-2',
  'kitty.exe':           'ti-terminal-2',
  'wezterm.exe':         'ti-terminal-2',
  'warp.exe':            'ti-terminal-2',
  'hyper.exe':           'ti-terminal-2',
  'tabby.exe':           'ti-terminal-2',
  'wt.exe':              'ti-terminal-2',

  // ── Version Control & API ──
  'githubdesktop.exe':   'ti-brand-github',
  'github desktop.exe':  'ti-brand-github',
  'gitkraken.exe':       'ti-brand-git',
  'sourcetree.exe':      'ti-git-branch',
  'fork.exe':            'ti-git-fork',
  'git.exe':             'ti-brand-git',
  'postman.exe':         'ti-api',
  'insomnia.exe':        'ti-api',
  'bruno.exe':           'ti-api',
  'tableplus.exe':       'ti-table',
  'dbeaver.exe':         'ti-database',
  'heidisql.exe':        'ti-database',
  'mysqlworkbench.exe':  'ti-database',
  'pgadmin4.exe':        'ti-database',
  'mongodbcompass.exe':  'ti-brand-mongodb',
  'azure data studio.exe': 'ti-database',
  'docker desktop.exe':  'ti-brand-docker',

  // ── Communication ──
  'discord.exe':         'ti-brand-discord',
  'discordcanary.exe':   'ti-brand-discord',
  'discordptb.exe':      'ti-brand-discord',
  'slack.exe':           'ti-brand-slack',
  'teams.exe':           'ti-brand-teams',
  'zoom.exe':            'ti-brand-zoom',
  'wpp.exe':             'ti-brand-whatsapp',
  'whatsapp.exe':        'ti-brand-whatsapp',
  'telegram.exe':        'ti-brand-telegram',
  'signal.exe':          'ti-brand-signal',
  'skype.exe':           'ti-brand-skype',
  'messenger.exe':       'ti-brand-messenger',
  'line.exe':            'ti-brand-line',
  'wechat.exe':          'ti-brand-wechat',
  'mattermost.exe':      'ti-brand-mattermost',
  'outlook.exe':         'ti-brand-outlook',
  'thunderbird.exe':     'ti-mail',
  'spark.exe':           'ti-mail',

  // ── Design & Creative ──
  'figma.exe':           'ti-brand-figma',
  'figma agent.exe':     'ti-brand-figma',
  'photoshop.exe':       'ti-brand-adobe',
  'illustrator.exe':     'ti-brand-adobe',
  'xd.exe':              'ti-brand-adobe',
  'premiere.exe':        'ti-brand-adobe',
  'afterfx.exe':         'ti-brand-adobe',
  'lightroom.exe':       'ti-brand-adobe',
  'indesign.exe':        'ti-brand-adobe',
  'blender.exe':         'ti-brand-blender',
  'inkscape.exe':        'ti-vector',
  'gimp.exe':            'ti-photo',
  'gimp-2.10.exe':       'ti-photo',
  'paint.net.exe':       'ti-photo',
  'paintdotnet.exe':     'ti-photo',
  'mspaint.exe':         'ti-brush',
  'affinity designer.exe':'ti-vector',
  'affinity photo.exe':  'ti-photo',
  'affinity.exe':        'ti-vector',
  'sketch.exe':          'ti-pencil',
  'resolve.exe':         'ti-movie',
  'obs64.exe':           'ti-brand-obs',
  'obs.exe':             'ti-brand-obs',

  // ── Productivity & Docs ──
  'winword.exe':         'ti-brand-office',
  'excel.exe':           'ti-table',
  'powerpnt.exe':        'ti-presentation',
  'onenote.exe':         'ti-notebook',
  'msaccess.exe':        'ti-database',
  'mspub.exe':           'ti-book',
  'notion.exe':          'ti-brand-notion',
  'obsidian.exe':        'ti-crystal-ball',
  'logseq.exe':          'ti-notes',
  'evernote.exe':        'ti-brand-evernote',
  'bear.exe':            'ti-notes',
  'typora.exe':          'ti-markdown',
  'todoist.exe':         'ti-checklist',
  'ticktick.exe':        'ti-checklist',
  'things.exe':          'ti-check',
  'trello.exe':          'ti-layout-board',
  'linear.exe':          'ti-layout-board',
  'clickup.exe':         'ti-checklist',

  // ── Media & Entertainment ──
  'spotify.exe':         'ti-brand-spotify',
  'vlc.exe':             'ti-player-play',
  'mpc-hc.exe':          'ti-player-play',
  'mpc-hc64.exe':        'ti-player-play',
  'mpv.exe':             'ti-player-play',
  'wmplayer.exe':        'ti-player-play',
  'itunes.exe':          'ti-brand-apple',
  'foobar2000.exe':      'ti-music',
  'music.ui.exe':        'ti-music',
  'photosapp.exe':       'ti-photo',
  'youtube':             'ti-brand-youtube',
  'twitch':              'ti-brand-twitch',

  // ── Games & Launchers ──
  'steam.exe':           'ti-brand-steam',
  'epicgameslauncher.exe':'ti-device-gamepad',
  'goggalaxy.exe':       'ti-device-gamepad',
  'battle.net.exe':      'ti-device-gamepad',
  'ubisoftconnect.exe':  'ti-device-gamepad',
  'riot client.exe':     'ti-device-gamepad',
  'ea app.exe':          'ti-device-gamepad',
  'rockstar games launcher.exe': 'ti-device-gamepad',
  'unity.exe':           'ti-brand-unity',
  'ue4editor.exe':       'ti-brand-unreal',
  'godot.exe':           'ti-brand-godot',
  'minecraft.exe':       'ti-brand-minecraft',
  'valorant.exe':        'ti-target-arrow',
  'league of legends.exe':'ti-target-arrow',
  'leagueclient.exe':    'ti-target-arrow',
  'cs2.exe':             'ti-target-arrow',
  'csgo.exe':            'ti-target-arrow',
  'overwatch.exe':       'ti-target-arrow',
  'fortnite.exe':        'ti-target-arrow',
  'destiny2.exe':        'ti-target-arrow',

  // ── Cloud & Storage ──
  'dropbox.exe':         'ti-brand-dropbox',
  'onedrive.exe':        'ti-brand-onedrive',
  'googledrivefs.exe':   'ti-brand-google-drive',
  'box.exe':             'ti-box',
  'mega.exe':            'ti-cloud',

  // ── System & Utilities ──
  'explorer.exe':        'ti-folder',
  'taskmgr.exe':         'ti-activity',
  'regedit.exe':         'ti-settings',
  'control.exe':         'ti-adjustments',
  'snippingtool.exe':    'ti-scissors',
  'calculatorapp.exe':   'ti-calculator',
  'calc.exe':            'ti-calculator',
  'settings.exe':        'ti-settings-2',
  'systemsettings.exe':  'ti-settings-2',
  'mmc.exe':             'ti-settings-2',
  'devmgmt.exe':         'ti-device-desktop',
  'msinfo32.exe':        'ti-info-circle',
  'cleanmgr.exe':        'ti-broom',
  'magnify.exe':         'ti-zoom-in',
  'osk.exe':             'ti-keyboard',
  'charmap.exe':         'ti-file-text',
  'resmon.exe':          'ti-chart-area',
  'perfmon.exe':         'ti-chart-bar',
  'eventvwr.exe':        'ti-file-text',
  'services.msc':        'ti-settings-cog',
  'diskmgmt.msc':        'ti-server',
  'clipchamp.exe':       'ti-movie',
  'quickassist.exe':     'ti-screen-share',
  '7zfm.exe':            'ti-file-zip',
  '7zg.exe':             'ti-file-zip',
  'winrar.exe':          'ti-file-zip',
  'peazip.exe':          'ti-file-zip',
  'everything.exe':      'ti-search',
  'flow launcher.exe':   'ti-search',
  'flow-launcher.exe':   'ti-search',
  'keypirinha.exe':      'ti-search',
  'powertoys.exe':       'ti-tools',
  'microsoft powertoys.exe':'ti-tools',
  'powertoys.colorpickerui.exe':'ti-color-picker',
  'powertoys.powerrename.exe':'ti-file-rename',
  'autohotkey.exe':      'ti-script',
  'autohotkeyu64.exe':   'ti-script',
  'autohotkeyux.exe':    'ti-script',
  'greenshot.exe':       'ti-camera',
  'sharex.exe':          'ti-camera',
  'lightshot.exe':       'ti-camera',
  'snagit.exe':          'ti-camera',
  'ditto.exe':           'ti-clipboard',
  'clipboardfusion.exe': 'ti-clipboard',
  'voicemeeterpro.exe':  'ti-volume-2',
  'audacity.exe':        'ti-microphone',
  'handbrake.exe':       'ti-movie',
  'handbrake.worker.exe':'ti-movie',
  'rainmeter.exe':       'ti-device-desktop',
  'flux.exe':            'ti-sun',
  'applicationframehost.exe':'ti-layout-dashboard',
  'shellexperiencehost.exe':'ti-layout-dashboard',
  'searchapp.exe':       'ti-search',
  'screenclippinghost.exe':'ti-scissors',

  // ── Remote & FTP ──
  'anydesk.exe':         'ti-screen-share',
  'teamviewer.exe':      'ti-screen-share',
  'mstsc.exe':           'ti-screen-share',
  'putty.exe':           'ti-terminal-2',
  'winscp.exe':          'ti-file-upload',
  'filezilla.exe':       'ti-file-upload',
  'mobaxterm.exe':       'ti-terminal-2',

  // ── AI & LLM ──
  'chatgpt.exe':         'ti-brand-openai',
  'copilot.exe':         'ti-brand-github-copilot',

  // ── Monitoring & Tracking ──
  'timelens.exe':        'ti-clock-hour-4',
  'timelens.trayapp.exe':'ti-clock-hour-4',
  'activitywatch.exe':   'ti-chart-bar',
  'rescuetime.exe':      'ti-clock',
  'manictime.exe':       'ti-clock',
  'toggl track.exe':     'ti-clock',
  'clockify.exe':        'ti-clock',
  'wakatime.exe':        'ti-chart-bar',

  // ── PDF & Documents ──
  'sumatrapdf.exe':      'ti-file-type-pdf',
  'acrobat.exe':         'ti-file-type-pdf',
  'acrord32.exe':        'ti-file-type-pdf',
  'foxitphantom.exe':    'ti-file-type-pdf',
  'foxitpdfreader.exe':  'ti-file-type-pdf',
  'calibre.exe':         'ti-books',
  'kindle.exe':          'ti-book',

  // ── Domains (partial match fallbacks) ──
  'github.com':          'ti-brand-github',
  'gitlab.com':          'ti-brand-gitlab',
  'bitbucket.org':       'ti-brand-bitbucket',
  'stackoverflow.com':   'ti-brand-stackoverflow',
  'stackexchange.com':   'ti-brand-stackoverflow',
  'dev.to':              'ti-code',
  'medium.com':          'ti-brand-medium',
  'hashnode.com':        'ti-brand-hashnode',
  'jira':                'ti-brand-jira',
  'confluence':          'ti-brand-confluence',
  'figma.com':           'ti-brand-figma',
  'notion.so':           'ti-brand-notion',
  'linear.app':          'ti-brand-linear',
  'trello.com':          'ti-brand-trello',
  'asana.com':           'ti-brand-asana',
  'monday.com':          'ti-brand-monday',
  'basecamp.com':        'ti-brand-basecamp',
  'spotify.com':         'ti-brand-spotify',
  'discord.com':         'ti-brand-discord',
  'primevideo.com':      'ti-movie',
  'disneyplus.com':      'ti-movie',
  'hulu.com':            'ti-movie',
  'hbomax.com':          'ti-movie',
  'gmail.com':           'ti-mail',
  'mail.google.com':     'ti-mail',
  'outlook.com':         'ti-mail',
  'outlook.office.com':  'ti-mail',
  'protonmail.com':      'ti-mail',
  'calendar.google.com': 'ti-calendar',
  'docs.google.com':     'ti-file-text',
  'sheets.google.com':   'ti-file-spreadsheet',
  'slides.google.com':   'ti-presentation',
  'drive.google.com':    'ti-cloud',
  'dropbox.com':         'ti-brand-dropbox',
  'onedrive.com':        'ti-brand-onedrive',
  'copilot.microsoft.com': 'ti-brand-windows',
  'gemini.google.com':   'ti-brand-google',
  'perplexity.ai':       'ti-search',
  'trae.ai':             'ti-brand-vscode',
  'huggingface.co':      'ti-brand-huggingface',
  'anthropic.com':       'ti-sparkles',
  'amazon.com':          'ti-brand-amazon',
  'amazon.in':           'ti-brand-amazon',
  'ebay.com':            'ti-shopping-cart',
  'flipkart.com':        'ti-shopping-cart',
  'wikipedia.org':       'ti-brand-wikipedia',
  'translate.google.com':'ti-language',
  'maps.google.com':     'ti-map',
  'news.ycombinator.com':'ti-brand-ycombinator',
  'producthunt.com':     'ti-brand-producthunt',
  'dribbble.com':        'ti-brand-dribbble',
  'behance.net':         'ti-brand-behance',
  'codesandbox.io':      'ti-brand-codesandbox',
  'codepen.io':          'ti-brand-codepen',
  'replit.com':          'ti-brand-codesandbox',
  'vercel.com':          'ti-brand-vercel',
  'netlify.com':         'ti-brand-netlify',
  'heroku.com':          'ti-brand-heroku',
  'aws.amazon.com':      'ti-brand-aws',
  'console.cloud.google.com': 'ti-cloud',
  'azure.microsoft.com': 'ti-brand-azure',
  'portal.azure.com':    'ti-brand-azure',
  'docker.com':          'ti-brand-docker',
  'docker':              'ti-brand-docker',
  'npmjs.com':           'ti-brand-npm',
  'pypi.org':            'ti-brand-python',
  'crates.io':           'ti-box',
  'stackblitz.com':      'ti-brand-stackblitz',
  'vitejs.dev':          'ti-brand-vite',
  'svelte.dev':          'ti-brand-svelte',
  'react.dev':           'ti-brand-react',
  'vuejs.org':           'ti-brand-vue',
  'angular.dev':         'ti-brand-angular',
  'nextjs.org':          'ti-brand-nextjs',
  'nuxt.com':            'ti-brand-nuxt',
  'tailwindcss.com':     'ti-brand-tailwind',
  'getbootstrap.com':    'ti-brand-bootstrap',
  'prisma.io':           'ti-brand-prisma',
  'supabase.com':        'ti-brand-supabase',
  'firebase.google.com': 'ti-brand-firebase',
  'stripe.com':          'ti-brand-stripe',
  'paypal.com':          'ti-brand-paypal',
  'whatsapp.com':        'ti-brand-whatsapp',
  'telegram.org':        'ti-brand-telegram',
  'signal.org':          'ti-brand-signal',
  'slack.com':           'ti-brand-slack',
  'zoom.us':             'ti-brand-zoom',
  'meet.google.com':     'ti-video',
  'teams.microsoft.com': 'ti-brand-teams',
  'pinterest.com':       'ti-brand-pinterest',
  'snapchat.com':        'ti-brand-snapchat',
  'quora.com':           'ti-brand-reddit',
  'canva.com':           'ti-brand-canva',
  'framer.com':          'ti-brand-framer',
  'loom.com':            'ti-brand-loom',
  'soundcloud.com':      'ti-brand-soundcloud',
  'music.youtube.com':   'ti-music',
  'notion.com':          'ti-brand-notion',
  'udemy.com':           'ti-school',
  'coursera.org':        'ti-school',
  'khanacademy.org':     'ti-school',
  'pluralsight.com':     'ti-school',
  'leetcode.com':        'ti-code',
  'hackerrank.com':      'ti-brand-hackerrank',
  'codeforces.com':       'ti-brand-codewars',
  'codewars.com':        'ti-brand-codewars',
  'exercism.org':        'ti-brand-exercism',
  'arxiv.org':           'ti-file-text',
  'scholar.google.com':  'ti-school',
  'node.exe':            'ti-brand-nodejs',
  'rancher desktop.exe': 'ti-brand-docker',
};

// Category fallback icons (use in Timeline blocks, etc.)
export const categoryIcons: Record<string, string> = {
  'development':   'ti-code',
  'browsing':      'ti-world',
  'communication': 'ti-message',
  'media':         'ti-player-play',
  'design':        'ti-vector',
  'documents':     'ti-file-text',
  'system':        'ti-settings-2',
  'gaming':        'ti-device-gamepad',
  'productivity':  'ti-checklist',
  'work':          'ti-checklist',
  'social':        'ti-users',
  'news':          'ti-news',
  'finance':       'ti-cash',
  'education':     'ti-school',
  'health':        'ti-heart',
  'utilities':     'ti-tools',
  'other':         'ti-dots',
  'idle':          'ti-moon',
  'away':          'ti-moon',
  'gap':           'ti-dots',
};

export function appIcon(exeName: string): string | null {
  const key = exeName.toLowerCase();
  if (iconMap[key]) return iconMap[key];
  const name = key.endsWith('.exe') ? key.slice(0, -4) : key;
  for (const [k, v] of Object.entries(iconMap)) {
    const kbase = k.toLowerCase();
    if (kbase.endsWith('.exe') ? kbase.slice(0, -4) === name : kbase === name) return v;
    if (key.includes(kbase)) return v;
  }
  return null;
}
