const iconMap: Record<string, string> = {
  // IDEs & Editors
  'code.exe':                    'ti-brand-vscode',
  'cursor.exe':                  'ti-brand-vscode',
  'windsurf.exe':                'ti-brand-vscode',
  'opencode.exe':                'ti-terminal-2',
  'devenv.exe':                  'ti-brand-visual-studio',
  'rider64.exe':                 'ti-brand-rider',
  'rider.exe':                   'ti-brand-rider',
  'idea64.exe':                  'ti-brand-intellij',
  'idea.exe':                    'ti-brand-intellij',
  'pycharm64.exe':               'ti-brand-pycharm',
  'pycharm.exe':                 'ti-brand-pycharm',
  'webstorm64.exe':              'ti-brand-webstorm',
  'webstorm.exe':                'ti-brand-webstorm',
  'phpstorm64.exe':              'ti-brand-php',
  'phpstorm.exe':                'ti-brand-php',
  'goland64.exe':                'ti-brand-golang',
  'goland.exe':                  'ti-brand-golang',
  'clion64.exe':                 'ti-brand-clion',
  'clion.exe':                   'ti-brand-clion',
  'datagrip64.exe':              'ti-database',
  'datagrip.exe':                'ti-database',
  'dataspell64.exe':             'ti-database',
  'dataspell.exe':               'ti-database',
  'sublime_text.exe':            'ti-brand-sublime',
  'notepad++.exe':               'ti-file-code',
  'notepadplusplus.exe':         'ti-file-code',
  'atom.exe':                    'ti-brand-atom',
  'vim.exe':                     'ti-file-code',
  'gvim.exe':                    'ti-file-code',
  'neovide.exe':                 'ti-file-code',
  'zed.exe':                     'ti-file-code',
  'trae.exe':                    'ti-code',
  'trae_cn.exe':                 'ti-code',
  'android studio.exe':          'ti-brand-android',
  'xcode.exe':                   'ti-brand-x',
  'eclipse.exe':                 'ti-brand-eclipse',

  // Design
  'figma.exe':                   'ti-brand-figma',
  'figma agent.exe':             'ti-brand-figma',
  'photoshop.exe':               'ti-photo',
  'illustrator.exe':             'ti-brush',
  'indesign.exe':                'ti-book',
  'afterfx.exe':                 'ti-movie',
  'premiere.exe':                'ti-movie',
  'blender.exe':                 'ti-box',
  'affinity designer.exe':       'ti-brush',
  'affinity photo.exe':          'ti-photo',
  'gimp.exe':                    'ti-photo',
  'inkscape.exe':                'ti-brush',
  'paint.net.exe':               'ti-photo',
  'paintdotnet.exe':             'ti-photo',
  'mspaint.exe':                 'ti-photo',

  // Browsers
  'chrome.exe':                  'ti-brand-chrome',
  'msedge.exe':                  'ti-brand-edge',
  'microsoftedge.exe':           'ti-brand-edge',
  'firefox.exe':                 'ti-brand-firefox',
  'brave.exe':                   'ti-brand-brave',
  'zen.exe':                     'ti-brand-firefox',
  'opera.exe':                   'ti-brand-opera',
  'vivaldi.exe':                 'ti-brand-vivaldi',
  'arc.exe':                     'ti-brand-arc',
  'thorium.exe':                 'ti-brand-chrome',

  // Communication
  'discord.exe':                 'ti-brand-discord',
  'discordcanary.exe':           'ti-brand-discord',
  'discordptb.exe':              'ti-brand-discord',
  'slack.exe':                   'ti-brand-slack',
  'teams.exe':                   'ti-brand-teams',
  'zoom.exe':                    'ti-brand-zoom',
  'telegram.exe':                'ti-brand-telegram',
  'whatsapp.exe':                'ti-brand-whatsapp',
  'signal.exe':                  'ti-brand-signal',
  'thunderbird.exe':             'ti-mail',
  'skype.exe':                   'ti-brand-skype',
  'messenger.exe':               'ti-brand-messenger',
  'line.exe':                    'ti-brand-line',
  'wechat.exe':                  'ti-brand-wechat',

  // Productivity & Notes
  'notion.exe':                  'ti-brand-notion',
  'obsidian.exe':                 'ti-brand-notion',
  'logseq.exe':                  'ti-notebook',
  'onenote.exe':                 'ti-notebook',
  'evernote.exe':                'ti-notebook',
  'todoist.exe':                 'ti-checklist',
  'ticktick.exe':                'ti-checklist',
  'trello.exe':                  'ti-layout-board',
  'linear.exe':                  'ti-layout-board',
  'clickup.exe':                 'ti-checklist',

  // Office
  'excel.exe':                   'ti-file-spreadsheet',
  'winword.exe':                 'ti-file-text',
  'powerpnt.exe':                'ti-presentation',
  'outlook.exe':                 'ti-mail',
  'msaccess.exe':                'ti-database',
  'mspub.exe':                   'ti-book',

  // Terminals
  'terminal.exe':                'ti-terminal-2',
  'windowsterminal.exe':         'ti-terminal-2',
  'wt.exe':                      'ti-terminal-2',
  'cmd.exe':                     'ti-terminal-2',
  'powershell.exe':              'ti-terminal-2',
  'pwsh.exe':                    'ti-terminal-2',
  'conhost.exe':                 'ti-terminal-2',
  'alacritty.exe':               'ti-terminal-2',
  'kitty.exe':                   'ti-terminal-2',
  'wezterm.exe':                 'ti-terminal-2',
  'warp.exe':                    'ti-terminal-2',
  'tabby.exe':                   'ti-terminal-2',
  'hyper.exe':                   'ti-terminal-2',

  // Git & Dev tools
  'git-bash.exe':                'ti-brand-git',
  'github desktop.exe':          'ti-brand-github',
  'gitkraken.exe':               'ti-brand-git',
  'sourcetree.exe':              'ti-brand-git',
  'fork.exe':                    'ti-brand-git',
  'git.exe':                     'ti-brand-git',
  'postman.exe':                 'ti-api',
  'insomnia.exe':                'ti-api',
  'dbeaver.exe':                 'ti-database',
  'heidisql.exe':                'ti-database',
  'mysqlworkbench.exe':          'ti-database',
  'pgadmin4.exe':                'ti-database',
  'azure data studio.exe':       'ti-database',
  'docker desktop.exe':          'ti-brand-docker',
  'docker':                      'ti-brand-docker',
  'rancher desktop.exe':         'ti-brand-docker',
  'wsl.exe':                     'ti-terminal-2',
  'ubuntu.exe':                  'ti-terminal-2',
  'debian.exe':                  'ti-terminal-2',
  'node.exe':                    'ti-brand-nodejs',

  // System & Utilities
  'applicationframehost.exe':      'ti-brand-windows',
  'systemsettings.exe':            'ti-settings-2',
  'explorer.exe':                  'ti-folder',
  'searchapp.exe':                 'ti-search',
  'screenclippinghost.exe':        'ti-scissors',
  'taskmgr.exe':                 'ti-chart-dots',
  'notepad.exe':                 'ti-notes',
  'snippingtool.exe':            'ti-camera',
  'calculatorapp.exe':           'ti-calculator',
  'calc.exe':                    'ti-calculator',
  'settings.exe':                'ti-settings-2',
  'control.exe':                 'ti-settings-2',
  'regedit.exe':                 'ti-file-code',
  'mmc.exe':                     'ti-settings-2',
  'devmgmt.exe':                 'ti-device-desktop',
  'msinfo32.exe':                'ti-info-circle',
  'cleanmgr.exe':                'ti-broom',
  'magnify.exe':                 'ti-zoom-in',
  'osk.exe':                     'ti-keyboard',
  'charmap.exe':                 'ti-file-text',
  'resmon.exe':                  'ti-chart-area',
  'perfmon.exe':                 'ti-chart-bar',
  'services.msc':                'ti-settings-cog',
  'diskmgmt.msc':                'ti-server',
  'eventvwr.exe':                'ti-file-text',
  'clipchamp.exe':               'ti-movie',
  'quickassist.exe':             'ti-screen-share',

  // Remote & FTP
  'anydesk.exe':                 'ti-screen-share',
  'teamviewer.exe':              'ti-screen-share',
  'mstsc.exe':                   'ti-screen-share',
  'putty.exe':                   'ti-terminal-2',
  'winscp.exe':                  'ti-file-upload',
  'filezilla.exe':               'ti-file-upload',
  'mobaxterm.exe':               'ti-terminal-2',

  // Media & Entertainment
  'spotify.exe':                 'ti-brand-spotify',
  'vlc.exe':                     'ti-player-play',
  'mpc-hc64.exe':                'ti-player-play',
  'mpc-hc.exe':                  'ti-player-play',
  'mpv.exe':                     'ti-player-play',
  'music.ui.exe':                'ti-music',
  'wmplayer.exe':                'ti-music',
  'photosapp.exe':               'ti-photo',
  'netflix':                     'ti-movie',
  'youtube':                     'ti-brand-youtube',
  'twitch':                      'ti-brand-twitch',

  // Gaming
  'steam.exe':                     'ti-brand-steam',
  'epicgameslauncher.exe':         'ti-brand-epic',
  'ubisoftconnect.exe':            'ti-brand-ubisoft',
  'battle.net.exe':                'ti-brand-battlenet',
  'riot client.exe':               'ti-sword',
  'ea app.exe':                    'ti-brand-ea',
  'minecraft.exe':                 'ti-box',
  'rockstar games launcher.exe':   'ti-brand-rockstar',
  'valorant-win64-shipping.exe':   'ti-brand-valorant',
  'valorant.exe':                  'ti-brand-valorant',
  'league of legends.exe':         'ti-sword',
  'leagueclient.exe':              'ti-sword',
  'cs2.exe':                       'ti-target-arrow',
  'csgo.exe':                      'ti-target-arrow',
  'r5apex.exe':                    'ti-target-arrow',
  'fortniteclient-win64-shipping.exe': 'ti-target-arrow',
  'fortnite.exe':                  'ti-target-arrow',
  'overwatch.exe':                 'ti-target-arrow',
  'warzone.exe':                   'ti-target-arrow',
  'call of duty.exe':              'ti-target-arrow',
  'rainbowsix.exe':                'ti-shield',
  'escapefromtarkov.exe':          'ti-shield',
  'destiny2.exe':                  'ti-target-arrow',
  'genshinimpact.exe':             'ti-sword',
  'among us.exe':                  'ti-users',

  // Browsers & Web (partial matches)
  'github.com':                  'ti-brand-github',
  'gitlab.com':                  'ti-brand-gitlab',
  'bitbucket.org':               'ti-brand-bitbucket',
  'stackoverflow.com':           'ti-brand-stackoverflow',
  'stackexchange.com':          'ti-brand-stackoverflow',
  'dev.to':                      'ti-code',
  'medium.com':                  'ti-brand-medium',
  'hashnode.com':                'ti-brand-hashnode',
  'jira':                        'ti-brand-jira',
  'confluence':                  'ti-brand-confluence',
  'figma.com':                   'ti-brand-figma',
  'notion.so':                   'ti-brand-notion',
  'linear.app':                  'ti-layout-board',
  'trello.com':                  'ti-brand-trello',
  'asana.com':                   'ti-brand-asana',
  'monday.com':                  'ti-brand-monday',
  'basecamp.com':                'ti-brand-basecamp',
  'spotify.com':                 'ti-brand-spotify',
  'discord.com':                 'ti-brand-discord',
  'reddit.com':                  'ti-brand-reddit',
  'twitter.com':                 'ti-brand-twitter',
  'x.com':                       'ti-brand-x',
  'youtube.com':                 'ti-brand-youtube',
  'twitch.tv':                   'ti-brand-twitch',
  'netflix.com':                 'ti-movie',
  'primevideo.com':              'ti-movie',
  'disneyplus.com':              'ti-movie',
  'hulu.com':                    'ti-movie',
  'hbomax.com':                  'ti-movie',
  'gmail.com':                   'ti-mail',
  'mail.google.com':             'ti-mail',
  'outlook.com':                 'ti-mail',
  'outlook.office.com':          'ti-mail',
  'protonmail.com':              'ti-mail',
  'calendar.google.com':         'ti-calendar',
  'docs.google.com':             'ti-file-text',
  'sheets.google.com':           'ti-file-spreadsheet',
  'slides.google.com':           'ti-presentation',
  'drive.google.com':            'ti-cloud',
  'dropbox.com':                 'ti-brand-dropbox',
  'onedrive.com':                'ti-brand-onedrive',
  'chatgpt.com':                 'ti-brand-openai',
  'claude.ai':                   'ti-brand-google',
  'copilot.microsoft.com':        'ti-brand-windows',
  'gemini.google.com':           'ti-brand-google',
  'perplexity.ai':               'ti-search',
  'localhost':                    'ti-server',
  '127.0.0.1':                   'ti-server',
  'amazon.com':                  'ti-brand-amazon',
  'amazon.in':                   'ti-brand-amazon',
  'ebay.com':                    'ti-shopping-cart',
  'flipkart.com':                'ti-shopping-cart',
  'wikipedia.org':               'ti-brand-wikipedia',
  'translate.google.com':        'ti-language',
  'maps.google.com':             'ti-map',
  'news.ycombinator.com':        'ti-brand-ycombinator',
  'producthunt.com':             'ti-brand-producthunt',
  'dribbble.com':                'ti-brand-dribbble',
  'behance.net':                 'ti-brand-behance',
  'codesandbox.io':              'ti-brand-codesandbox',
  'codepen.io':                  'ti-brand-codepen',
  'replit.com':                  'ti-brand-codesandbox',
  'vercel.com':                  'ti-brand-vercel',
  'netlify.com':                 'ti-brand-netlify',
  'heroku.com':                  'ti-brand-heroku',
  'aws.amazon.com':              'ti-cloud',
  'console.cloud.google.com':    'ti-cloud',
  'azure.microsoft.com':         'ti-cloud',
  'docker.com':                  'ti-brand-docker',
  'npmjs.com':                   'ti-brand-npm',
  'pypi.org':                    'ti-brand-python',
  'crates.io':                   'ti-box',
  'stackblitz.com':              'ti-brand-stackblitz',
  'vitejs.dev':                  'ti-brand-vite',
  'svelte.dev':                  'ti-brand-svelte',
  'react.dev':                   'ti-brand-react',
  'vuejs.org':                   'ti-brand-vue',
  'angular.dev':                 'ti-brand-angular',
  'nextjs.org':                  'ti-brand-nextjs',
  'nuxt.com':                    'ti-brand-nuxt',
  'tailwindcss.com':             'ti-brand-tailwind',
  'getbootstrap.com':            'ti-brand-bootstrap',
  'prisma.io':                   'ti-brand-prisma',
  'supabase.com':                'ti-brand-supabase',
  'firebase.google.com':         'ti-brand-firebase',
  'stripe.com':                  'ti-brand-stripe',
  'paypal.com':                  'ti-brand-paypal',
  'whatsapp.com':                'ti-brand-whatsapp',
  'telegram.org':                'ti-brand-telegram',
  'signal.org':                  'ti-brand-signal',
  'slack.com':                   'ti-brand-slack',
  'zoom.us':                     'ti-brand-zoom',
  'meet.google.com':             'ti-video',
  'teams.microsoft.com':         'ti-brand-teams',
  'linkedin.com':                'ti-brand-linkedin',
  'instagram.com':               'ti-brand-instagram',
  'facebook.com':                'ti-brand-facebook',
  'tiktok.com':                  'ti-brand-tiktok',
  'pinterest.com':               'ti-brand-pinterest',
  'snapchat.com':                'ti-brand-snapchat',
  'quora.com':                   'ti-brand-reddit',
  'udemy.com':                   'ti-school',
  'coursera.org':                'ti-school',
  'khanacademy.org':             'ti-school',
  'pluralsight.com':             'ti-school',
  'leetcode.com':                'ti-code',
  'hackerrank.com':              'ti-code',
  'codeforces.com':              'ti-code',
  'codewars.com':                'ti-code',
  'exercism.org':                'ti-code',
  'openai.com':                  'ti-brand-openai',
  'anthropic.com':               'ti-brand-google',
  'huggingface.co':              'ti-brand-huggingface',
  'arxiv.org':                   'ti-file-text',
  'scholar.google.com':          'ti-school',

  // PDF & Documents
  'sumatrapdf.exe':              'ti-file-type-pdf',
  'acrobat.exe':                 'ti-file-type-pdf',
  'acrord32.exe':                'ti-file-type-pdf',
  'foxitphantom.exe':            'ti-file-type-pdf',
  'foxitpdfreader.exe':          'ti-file-type-pdf',
  'calibre.exe':                 'ti-books',
  'kindle.exe':                  'ti-book',

  // Archive & Files
  '7zfm.exe':                    'ti-file-zip',
  '7zg.exe':                     'ti-file-zip',
  'winrar.exe':                  'ti-file-zip',
  'peazip.exe':                  'ti-file-zip',

  // Other
  'everything.exe':              'ti-search',
  'flow launcher.exe':           'ti-search',
  'powertoys.exe':               'ti-tool',
  'powertoys.colorpickerui.exe': 'ti-color-picker',
  'powertoys.powerrename.exe':   'ti-file-rename',
  'microsoft powertoys.exe':     'ti-tool',
  'sharex.exe':                  'ti-camera',
  'greenshot.exe':               'ti-camera',
  'lightshot.exe':               'ti-camera',
  'ditto.exe':                   'ti-clipboard',
  'clipboardfusion.exe':         'ti-clipboard',
  'snagit.exe':                  'ti-camera',
  'obs64.exe':                   'ti-video',
  'obs.exe':                     'ti-video',
  'autohotkey.exe':              'ti-keyboard',
  'autohotkeyu64.exe':           'ti-keyboard',
  'autohotkeyux.exe':            'ti-keyboard',
  'voicemeeterpro.exe':          'ti-volume-2',
  'audacity.exe':                'ti-microphone',
  'handbrake.exe':               'ti-movie',
  'handbrake.worker.exe':        'ti-movie',

  // AI & LLM tools
  'chatgpt.exe':                   'ti-brand-openai',
  'copilot.exe':                   'ti-brand-windows',

  // Monitoring & Tracking
  'timelens.exe':                  'ti-clock-hour-4',
  'timelens.trayapp.exe':          'ti-clock-hour-4',
  'activitywatch.exe':             'ti-chart-bar',
  'rescuetime.exe':                'ti-clock',
  'manictime.exe':                  'ti-clock',
  'toggl track.exe':               'ti-clock',
  'clockify.exe':                  'ti-clock',
  'wakatime.exe':                  'ti-chart-bar',
};

export function appIcon(exeName: string): string | null {
  const key = exeName.toLowerCase();
  if (iconMap[key]) return iconMap[key];
  const name = key.endsWith('.exe') ? key.slice(0, -4) : key;
  for (const [k, v] of Object.entries(iconMap)) {
    const kbase = k.toLowerCase();
    if (kbase.endsWith('.exe') ? kbase.slice(0, -4) === name : kbase === name) return v;
    if (key.includes(kbase)) return v;
  }
  return null;
}
